#!/bin/sh
#
# Writes the final sources.list file
#

CHROOT=$(mount | grep proc | grep calamares | awk '{print $3}' | sed -e "s#/proc##g")
DEBIAN_RELEASE="bookworm"
KAMU_RELEASE="cheetah"

cat << EOF > $CHROOT/etc/apt/sources.list
# See https://wiki.debian.org/SourcesList for more information.
deb http://deb.debian.org/debian $DEBIAN_RELEASE main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian $DEBIAN_RELEASE main contrib non-free non-free-firmware

deb http://deb.debian.org/debian $DEBIAN_RELEASE-updates main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian $DEBIAN_RELEASE-updates main contrib non-free non-free-firmware

deb http://security.debian.org/debian-security/ $DEBIAN_RELEASE-security main contrib non-free non-free-firmware
deb-src http://security.debian.org/debian-security/ $DEBIAN_RELEASE-security main contrib non-free non-free-firmware

# Backports allow you to install newer versions of software made available for this release
deb http://deb.debian.org/debian $DEBIAN_RELEASE-backports main contrib non-free non-free-firmware
deb-src http://deb.debian.org/debian $DEBIAN_RELEASE-backports main contrib non-free non-free-firmware

# Kamuriki's Repository
deb [arch=amd64] https://sourceforge.net/projects/kamurikilinux/files/kamuriki $KAMU_RELEASE main

# WineHQ's Repository
deb https://dl.winehq.org/wine-builds/debian $DEBIAN_RELEASE main

# Multimedia PPA
deb https://deb-multimedia.org/debian $DEBIAN_RELEASE main non-free
deb-src https://deb-multimedia.org/debian $DEBIAN_RELEASE main non-free

EOF

exit 0
